[package]
name = "aoc25"
version = "0.0.1"
edition = "2024"

[dependencies]
aoclib-rs = { git = "https://github.com/glennhartmann/aoclib-rs.git", tag = "v0.0.14" }

clap = { version = "4.5.51", features = ["derive"] }
